ALTER TABLE cms_services
  ADD COLUMN IF NOT EXISTS homepage_tab_title text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS homepage_short_description text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS business_benefits jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS show_on_homepage boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS cms_services_homepage_showcase_idx
  ON cms_services (sort_order)
  WHERE status = 'published' AND show_on_homepage = true AND deleted_at IS NULL;

INSERT INTO cms_services (
  id,
  title,
  slug,
  excerpt,
  body,
  category,
  tags,
  icon,
  features,
  sort_order,
  homepage_tab_title,
  homepage_short_description,
  business_benefits,
  show_on_homepage,
  short_hero_description,
  long_intro_heading,
  long_intro_description,
  hero_cta_button_text,
  hero_cta_button_link,
  secondary_cta_button_text,
  secondary_cta_button_link,
  sub_services,
  benefits,
  why_choose_us,
  development_process,
  final_cta,
  status,
  published_at,
  seo_title,
  meta_description,
  focus_keyword,
  canonical_url,
  schema_type,
  sitemap_priority
) VALUES
(
  'service-data-analytics-business-intelligence',
  'Data Analytics & Business Intelligence',
  'data-analytics-business-intelligence',
  'Transform raw business data into clear dashboards, KPI systems, and strategic insights that help teams make faster and smarter decisions.',
  E'ADT SoftTech helps businesses convert scattered data into clear reporting systems, executive dashboards, and practical decision intelligence. We focus on making data easier to trust, explore, and act on across departments.\n\nOur analytics solutions support sales, finance, operations, customer behavior, and leadership visibility. From KPI planning to dashboard development, we design reporting environments that help teams see what matters faster.\n\nWe also support forecasting, business planning, and data quality improvements so your analytics system becomes a long-term operational asset.',
  'Data Analytics',
  '["Analytics","Business Intelligence","Power BI","Dashboards"]'::jsonb,
  'BarChart3',
  '["Power BI dashboards","Predictive analytics","Data visualization","KPI reporting","BI consulting","Strategic business insights"]'::jsonb,
  0,
  'Data Analytics & Business Intelligence',
  'Transform raw business data into clear dashboards, KPI systems, and strategic insights that help teams make faster and smarter decisions.',
  '["Interactive dashboards for performance tracking","KPI reporting and executive-level decision visibility","Sales, finance, operations, and customer analytics","Data-driven forecasting and business planning"]'::jsonb,
  true,
  'Dashboards, KPI systems, and business intelligence that turn raw data into confident decisions.',
  'Service Overview',
  E'We design analytics systems that connect business goals with measurable data. The result is a clear view of performance, opportunities, risks, and next actions.\n\nOur team can support the full workflow from data preparation and dashboard design to KPI strategy and executive reporting.',
  'Book Free Consultation',
  '/free-services',
  'Contact Us',
  '/contact',
  '[{"title":"Power BI and executive dashboards","description":"Interactive reports for leaders and operational teams.","order":0},{"title":"KPI reporting systems","description":"Track the metrics that define growth, delivery, finance, and customer outcomes.","order":1},{"title":"Sales, finance, and operations analytics","description":"Clean views into business performance across departments.","order":2},{"title":"Forecasting and planning models","description":"Use trends and scenarios to support smarter business planning.","order":3}]'::jsonb,
  '[{"title":"Faster decision-making","description":"Teams get one clear source for daily and strategic performance.","order":0},{"title":"Improved visibility","description":"Leadership can see trends, gaps, and priorities without manual reporting delays.","order":1},{"title":"Better planning","description":"Forecasting and KPI tracking support proactive business moves.","order":2},{"title":"Reduced reporting effort","description":"Automated dashboards cut repetitive spreadsheet work.","order":3}]'::jsonb,
  '[{"title":"Practical solutions","description":"We build dashboards around real business questions, not vanity metrics.","order":0},{"title":"Business-focused approach","description":"Every KPI is tied to decisions and outcomes.","order":1},{"title":"Scalable systems","description":"Reporting structures can grow as data and departments expand.","order":2},{"title":"Ongoing support","description":"We help maintain, improve, and extend your analytics setup.","order":3}]'::jsonb,
  '[{"stepNumber":1,"title":"Discovery","description":"Understand business goals, data sources, and reporting pain points.","order":0},{"stepNumber":2,"title":"Strategy","description":"Define KPIs, dashboard structure, and decision workflows.","order":1},{"stepNumber":3,"title":"Design / Planning","description":"Map data models, visuals, and user journeys.","order":2},{"stepNumber":4,"title":"Development / Implementation","description":"Build dashboards, pipelines, measures, and reports.","order":3},{"stepNumber":5,"title":"Testing","description":"Validate data quality, calculations, and usability.","order":4},{"stepNumber":6,"title":"Support & Optimization","description":"Improve reporting performance and add new business views over time.","order":5}]'::jsonb,
  '{"heading":"Ready to discuss your project?","paragraph":"Talk with ADT SoftTech about dashboards, KPIs, and business intelligence systems that fit your workflow.","buttonText":"Get Free Consultation","buttonUrl":"/free-services"}'::jsonb,
  'published',
  now(),
  'Data Analytics & Business Intelligence Services | ADT SoftTech',
  'Build dashboards, KPI systems, BI reporting, and forecasting solutions with ADT SoftTech.',
  'data analytics, business intelligence, dashboards, KPI reporting',
  '/services/data-analytics-business-intelligence',
  'Service',
  '0.7'
),
(
  'service-ai-automation',
  'AI & Automation',
  'ai-automation',
  'Build intelligent AI agents, chatbots, and automated workflows that reduce manual effort, speed up operations, and improve customer and team productivity.',
  E'ADT SoftTech builds AI and automation systems that help businesses remove repetitive work, improve response times, and make internal knowledge easier to use. We design practical AI workflows around your real tools, data, and team operations.\n\nOur solutions include AI chatbots, support assistants, internal knowledge systems, LLM integrations, RAG workflows, and AI-powered process automation.\n\nWe focus on reliability, business fit, and measurable productivity improvements so automation becomes a useful part of daily operations.',
  'AI Automation',
  '["AI","Automation","Chatbots","RAG","LLM"]'::jsonb,
  'Bot',
  '["AI chatbots","Intelligent agents","LLM integrations","RAG systems","Automation bots","N8N","Make.com","Zapier","Custom AI workflow automation"]'::jsonb,
  1,
  'AI & Automation',
  'Build intelligent AI agents, chatbots, and automated workflows that reduce manual effort, speed up operations, and improve customer and team productivity.',
  '["AI chatbots and support assistants","Workflow automation using AI and integrations","LLM, RAG, and internal knowledge systems","Reduced repetitive tasks and faster execution"]'::jsonb,
  true,
  'AI agents, chatbots, and workflow automation built to reduce manual effort and speed up execution.',
  'Service Overview',
  E'We help organizations identify where AI can create practical value, then build tools that fit existing systems and user habits.\n\nFrom customer support chatbots to internal knowledge assistants and automated workflows, we keep the implementation focused on real productivity gains.',
  'Book Free Consultation',
  '/free-services',
  'Contact Us',
  '/contact',
  '[{"title":"AI chatbots and assistants","description":"Customer support, internal helpdesk, and team productivity agents.","order":0},{"title":"LLM and RAG systems","description":"Knowledge systems that answer from approved documents and data.","order":1},{"title":"Workflow automation","description":"Connect tools, forms, CRMs, sheets, APIs, and notifications.","order":2},{"title":"AI integrations","description":"Add intelligent features into web apps, dashboards, and business systems.","order":3}]'::jsonb,
  '[{"title":"Reduced manual work","description":"Automation handles repetitive handoffs and routine tasks.","order":0},{"title":"Faster response times","description":"AI assistants support customers and teams instantly.","order":1},{"title":"Better knowledge access","description":"Teams can retrieve answers from internal materials faster.","order":2},{"title":"Improved consistency","description":"Defined workflows reduce missed steps and process variation.","order":3}]'::jsonb,
  '[{"title":"Practical solutions","description":"We start with workflow value before choosing AI complexity.","order":0},{"title":"Business-focused approach","description":"AI is designed around operational outcomes and user adoption.","order":1},{"title":"Scalable systems","description":"Architectures support expansion across teams and tools.","order":2},{"title":"Ongoing support","description":"We monitor, refine, and extend automations after launch.","order":3}]'::jsonb,
  '[{"stepNumber":1,"title":"Discovery","description":"Find repetitive work, data sources, and automation opportunities.","order":0},{"stepNumber":2,"title":"Strategy","description":"Define AI use cases, integrations, and success metrics.","order":1},{"stepNumber":3,"title":"Design / Planning","description":"Plan prompts, workflows, knowledge sources, and safeguards.","order":2},{"stepNumber":4,"title":"Development / Implementation","description":"Build agents, automations, integrations, and interfaces.","order":3},{"stepNumber":5,"title":"Testing","description":"Validate outputs, edge cases, permissions, and handoffs.","order":4},{"stepNumber":6,"title":"Support & Optimization","description":"Improve accuracy, adoption, and workflow coverage over time.","order":5}]'::jsonb,
  '{"heading":"Ready to discuss your project?","paragraph":"Talk with ADT SoftTech about AI agents, chatbots, and automation workflows for your business.","buttonText":"Get Free Consultation","buttonUrl":"/free-services"}'::jsonb,
  'published',
  now(),
  'AI & Automation Services | ADT SoftTech',
  'Build AI agents, chatbots, RAG systems, and workflow automation with ADT SoftTech.',
  'AI automation, AI agents, chatbots, RAG systems',
  '/services/ai-automation',
  'Service',
  '0.7'
),
(
  'service-web-development',
  'Web Development',
  'web-development',
  'Design and develop modern, scalable, and conversion-focused web platforms for businesses, SaaS products, dashboards, and custom digital systems.',
  E'ADT SoftTech develops web platforms that support real business workflows, customer journeys, and growth goals. We build websites, dashboards, SaaS products, client portals, and backend-connected systems with clean architecture.\n\nOur web development process covers planning, UI implementation, APIs, integrations, responsive behavior, security basics, and maintainability.\n\nThe result is a web platform that looks polished, works reliably, and can evolve as your business grows.',
  'Web Development',
  '["Web Development","SaaS","Client Portals","API Integrations"]'::jsonb,
  'Code2',
  '["Business websites","SaaS platforms","Custom web applications","API integrations","Long-term maintenance services"]'::jsonb,
  2,
  'Web Development',
  'Design and develop modern, scalable, and conversion-focused web platforms for businesses, SaaS products, dashboards, and custom digital systems.',
  '["Custom business websites and web applications","SaaS platforms and client portals","API integrations and backend-connected experiences","Responsive, secure, and growth-ready architecture"]'::jsonb,
  true,
  'Modern websites, SaaS products, dashboards, and web applications built for growth.',
  'Service Overview',
  E'We design and develop web systems that combine strong user experience with reliable engineering. Every build is shaped around the workflows, content, and integrations your business actually needs.\n\nWhether you need a public website, client portal, admin dashboard, or SaaS platform, we keep the product scalable and maintainable.',
  'Book Free Consultation',
  '/free-services',
  'Contact Us',
  '/contact',
  '[{"title":"Business websites","description":"Professional, responsive websites focused on credibility and conversion.","order":0},{"title":"Web applications","description":"Custom systems for internal teams and external users.","order":1},{"title":"SaaS platforms and portals","description":"Product foundations with dashboards, accounts, and workflows.","order":2},{"title":"API and backend integrations","description":"Connect your web experience to databases, CRMs, payment tools, and more.","order":3}]'::jsonb,
  '[{"title":"Stronger digital presence","description":"A polished web experience builds trust and supports conversion.","order":0},{"title":"Better operational workflows","description":"Custom web tools reduce manual processes and scattered systems.","order":1},{"title":"Scalable architecture","description":"Your platform can grow with features, users, and integrations.","order":2},{"title":"Responsive access","description":"Users get a clean experience across desktop, tablet, and mobile.","order":3}]'::jsonb,
  '[{"title":"Practical solutions","description":"We build around your business model and daily workflows.","order":0},{"title":"Business-focused approach","description":"Design and engineering choices support measurable goals.","order":1},{"title":"Scalable systems","description":"We plan structure, integrations, and maintainability early.","order":2},{"title":"Ongoing support","description":"We help improve, maintain, and extend the platform after launch.","order":3}]'::jsonb,
  '[{"stepNumber":1,"title":"Discovery","description":"Define goals, users, features, integrations, and constraints.","order":0},{"stepNumber":2,"title":"Strategy","description":"Plan architecture, milestones, content, and delivery priorities.","order":1},{"stepNumber":3,"title":"Design / Planning","description":"Create user flows, layouts, and interface direction.","order":2},{"stepNumber":4,"title":"Development / Implementation","description":"Build frontend, backend connections, APIs, and admin workflows.","order":3},{"stepNumber":5,"title":"Testing","description":"Test responsive behavior, forms, performance, and key journeys.","order":4},{"stepNumber":6,"title":"Support & Optimization","description":"Launch, monitor, improve, and scale the web platform.","order":5}]'::jsonb,
  '{"heading":"Ready to discuss your project?","paragraph":"Talk with ADT SoftTech about your website, SaaS platform, portal, or custom web system.","buttonText":"Get Free Consultation","buttonUrl":"/free-services"}'::jsonb,
  'published',
  now(),
  'Web Development Services | ADT SoftTech',
  'Build responsive business websites, SaaS platforms, portals, and web applications with ADT SoftTech.',
  'web development, SaaS development, web applications',
  '/services/web-development',
  'Service',
  '0.7'
),
(
  'service-mobile-application-development',
  'Mobile Application Development',
  'mobile-application-development',
  'Create high-performance Android and iOS mobile applications designed for real users, practical workflows, and business growth.',
  E'ADT SoftTech builds mobile applications for customer-facing products, business operations, and workflow systems. We focus on intuitive user experience, stable backend integration, and performance across Android and iOS.\n\nOur mobile app development service supports Flutter-based cross-platform delivery as well as practical planning for APIs, authentication, notifications, data flows, and long-term maintenance.\n\nWe design apps for real usage, clear navigation, and business outcomes, not just screens.',
  'Mobile Apps',
  '["Mobile Apps","Flutter","Android","iOS"]'::jsonb,
  'Smartphone',
  '["Flutter apps","Android/iOS solutions","Cross-platform products","Scalable mobile applications","Backend/API integration"]'::jsonb,
  3,
  'Mobile Application Development',
  'Create high-performance Android and iOS mobile applications designed for real users, practical workflows, and business growth.',
  '["Flutter-based cross-platform mobile apps","Android and iOS application development","Business workflow and customer-facing apps","Scalable UI, backend integration, and long-term support"]'::jsonb,
  true,
  'High-performance Android and iOS apps for customers, teams, and business workflows.',
  'Service Overview',
  E'We create mobile apps that feel clear, fast, and dependable for the people using them. The work starts with business goals and user workflows, then moves into design, development, integrations, and testing.\n\nOur Flutter expertise helps businesses launch cross-platform applications efficiently while keeping room for future growth.',
  'Book Free Consultation',
  '/free-services',
  'Contact Us',
  '/contact',
  '[{"title":"Flutter mobile apps","description":"Cross-platform apps for Android and iOS from one efficient codebase.","order":0},{"title":"Customer-facing applications","description":"Mobile experiences for booking, engagement, commerce, support, and more.","order":1},{"title":"Business workflow apps","description":"Operational tools for teams, approvals, field work, and reporting.","order":2},{"title":"Backend integration","description":"Connect apps to APIs, dashboards, authentication, databases, and notifications.","order":3}]'::jsonb,
  '[{"title":"Faster launch","description":"Cross-platform development can reduce duplicated effort.","order":0},{"title":"Better user access","description":"Customers and teams can complete key tasks from mobile devices.","order":1},{"title":"Integrated operations","description":"Apps connect mobile workflows with backend business systems.","order":2},{"title":"Long-term maintainability","description":"A scalable structure supports updates and feature expansion.","order":3}]'::jsonb,
  '[{"title":"Practical solutions","description":"We design apps around real user journeys and business needs.","order":0},{"title":"Business-focused approach","description":"Features are prioritized by value, usage, and launch goals.","order":1},{"title":"Scalable systems","description":"We plan backend integration and future enhancements from the start.","order":2},{"title":"Ongoing support","description":"We support fixes, improvements, and new releases after launch.","order":3}]'::jsonb,
  '[{"stepNumber":1,"title":"Discovery","description":"Understand users, workflows, platforms, and business goals.","order":0},{"stepNumber":2,"title":"Strategy","description":"Define MVP scope, technical approach, and release plan.","order":1},{"stepNumber":3,"title":"Design / Planning","description":"Map mobile screens, flows, UI states, and backend needs.","order":2},{"stepNumber":4,"title":"Development / Implementation","description":"Build the mobile app, APIs, integrations, and core features.","order":3},{"stepNumber":5,"title":"Testing","description":"Test usability, devices, performance, integrations, and edge cases.","order":4},{"stepNumber":6,"title":"Support & Optimization","description":"Launch, monitor, update, and improve the app over time.","order":5}]'::jsonb,
  '{"heading":"Ready to discuss your project?","paragraph":"Talk with ADT SoftTech about your Android, iOS, or Flutter mobile application.","buttonText":"Get Free Consultation","buttonUrl":"/free-services"}'::jsonb,
  'published',
  now(),
  'Mobile Application Development Services | ADT SoftTech',
  'Build Flutter, Android, and iOS apps for customer and business workflows with ADT SoftTech.',
  'mobile app development, Flutter apps, Android iOS apps',
  '/services/mobile-application-development',
  'Service',
  '0.7'
),
(
  'service-social-media-management',
  'Social Media Management',
  'social-media-management',
  'Strengthen digital presence through professional content planning, brand communication, audience engagement, and social platform management.',
  E'ADT SoftTech helps businesses manage their social presence with clear content planning, consistent brand communication, and practical performance tracking. We focus on keeping your online voice professional, active, and aligned with your business goals.\n\nOur social media management support can include posting strategy, platform calendars, engagement handling, and reporting.\n\nThe goal is to help your brand stay visible, credible, and consistent across the channels your customers use.',
  'Digital Marketing',
  '["Social Media","Content Planning","Brand Communication","Campaign Reporting"]'::jsonb,
  'Megaphone',
  '["Content planning","Posting strategy","Brand communication","Audience engagement","Campaign tracking","Monthly reporting"]'::jsonb,
  4,
  'Social Media Management',
  'Strengthen digital presence through professional content planning, brand communication, audience engagement, and social platform management.',
  '["Social media content planning and posting strategy","Brand consistency across platforms","Audience engagement and response management","Campaign tracking and monthly performance reporting"]'::jsonb,
  true,
  'Professional content planning, brand communication, engagement, and platform management.',
  'Service Overview',
  E'We help brands communicate more consistently across social channels with a structured content calendar and clear messaging direction. The work is practical, professional, and aligned with your target audience.\n\nOur process supports posting strategy, audience engagement, campaign tracking, and monthly reporting so social activity becomes easier to manage and measure.',
  'Book Free Consultation',
  '/free-services',
  'Contact Us',
  '/contact',
  '[{"title":"Content planning","description":"Create monthly content direction, post themes, and platform calendars.","order":0},{"title":"Posting strategy","description":"Plan timing, messaging, formats, and campaign priorities.","order":1},{"title":"Brand communication","description":"Keep visuals and language consistent across platforms.","order":2},{"title":"Performance reporting","description":"Track engagement, reach, campaign activity, and monthly progress.","order":3}]'::jsonb,
  '[{"title":"More consistent presence","description":"Your brand stays active with planned content and clear messaging.","order":0},{"title":"Improved audience engagement","description":"Timely responses and content planning support stronger relationships.","order":1},{"title":"Better campaign visibility","description":"Reports show what is working and where to improve.","order":2},{"title":"Professional brand image","description":"Consistent communication helps build trust across channels.","order":3}]'::jsonb,
  '[{"title":"Practical solutions","description":"We plan social media around business goals and audience behavior.","order":0},{"title":"Business-focused approach","description":"Content supports credibility, awareness, engagement, and lead flow.","order":1},{"title":"Scalable systems","description":"Calendars and reporting can expand as campaigns grow.","order":2},{"title":"Ongoing support","description":"We help manage, refine, and report social activity over time.","order":3}]'::jsonb,
  '[{"stepNumber":1,"title":"Discovery","description":"Understand brand voice, audience, platforms, and content goals.","order":0},{"stepNumber":2,"title":"Strategy","description":"Define content pillars, cadence, campaign direction, and reporting needs.","order":1},{"stepNumber":3,"title":"Design / Planning","description":"Prepare calendars, post ideas, messaging, and creative direction.","order":2},{"stepNumber":4,"title":"Development / Implementation","description":"Create, schedule, publish, and manage platform activity.","order":3},{"stepNumber":5,"title":"Testing","description":"Review engagement, audience response, and content performance.","order":4},{"stepNumber":6,"title":"Support & Optimization","description":"Adjust content strategy and reporting each month.","order":5}]'::jsonb,
  '{"heading":"Ready to discuss your project?","paragraph":"Talk with ADT SoftTech about content planning, platform management, and digital presence.","buttonText":"Get Free Consultation","buttonUrl":"/free-services"}'::jsonb,
  'published',
  now(),
  'Social Media Management Services | ADT SoftTech',
  'Manage content planning, brand communication, engagement, and social reporting with ADT SoftTech.',
  'social media management, content planning, brand communication',
  '/services/social-media-management',
  'Service',
  '0.7'
)
ON CONFLICT (slug) DO NOTHING;
